### ISSUE TITLE
Black screen when running release

### ISSUE THREAD

**Issue by Astronome1** [diharaw/volumetric-fog#1]
Hello there. I'm new to opengl so I just wanted to run the release build first, I am getting a black screen when running the file VolumetricLighting.exe with no errors in the terminal. I have extracted to a folder in my computer.
My configuration:
- Windows 10 21H2
- Intel Core i5 9400f with RX 580 gpu.. 
Again I might be doing something wrong and would appreciate feedback. Thanks in advance

**Comment by diharaw** [comment]
Fixed! It was caused by an AMD-specific bug related to 3D textures.
